name: CI/CD for flight-viewer-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag cerushady/flight_viewer_backend:$(date +%s) .

    - name: Push to DockerHub
      run: docker push cerushady/flight_viewer_backend:latest

  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest from DockerHub
        run: docker pull cerushady/flight_viewer_backend:latest

      - name: Delete existing container
        run: |
          if [ "$(docker ps -q -f name=flight_viewer_backend_cont)" ]; then
            sudo docker rm -f flight_viewer_backend_cont
          fi

      - name: Run container
        run: docker run -d -p 5000:5000 -e NODE_ENV=production -e API_URL=${{ secrets.FLIGHT_API_URL }} -e API_KEY=${{ secrets.FLIGHT_API_KEY }} --name flight_viewer_backend_cont cerushady/flight_viewer_backend
